FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN if [ -f package-lock.json ]; then \
        npm ci --silent ; \
    else \
        npm install --production --silent ; \
    fi
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]